import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainMenu from "./components/menu/MainMenu";
import { AuthProvider } from "./contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider >
          <body className={inter.className}>
            <div className=' overflow-y-auto background-image-main object-cover'>
                <MainMenu />      
                  <div className='mx-auto min-h-screen md:max-w-[1100px] px-5 md:block flex md:justify-between justify-center pt-28 '>
                    {children}
                  </div>
                <div className='w-full h-80 bg-white'></div>
            </div>
          </body>
      </AuthProvider>
    </html>
  );
}
